site_name: PyAction Cookiecutter
repo_name: lnxpy/cookiecutter-pyaction
repo_url: https://github.com/lnxpy/cookiecutter-pyaction
site_url: https://pyaction.imsadra.me/

nav:
  - PyAction: index.md
  - Demo Action: demo.md
  - Contributing: contributing.md
  - License: license.md
  - Contact Me: contact.md

theme:
  name: material
  features:
    - navigation.instant
    - content.code.copy
    - navigation.footer
    - search.highlight
    - content.code.annotate
  palette:
    scheme: slate
    # primary: amber
    accent: amber

  logo: img/logo.svg
  favicon: img/logo.svg
  icon:
    repo: fontawesome/brands/github

plugins:
  - social
  - search:
      lang: en

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lnxpy/cookiecutter-pyaction
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lnxpylnxpy
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/sadra-yahyapour
    - icon: fontawesome/solid/globe
      link: https://imsadra.me

extra_css:
  - css/navbar.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
