name: {{ cookiecutter.action_name }}
description: {{ cookiecutter.description }}
author: {{ cookiecutter.author_name }}

branding:
  icon: check
  color: blue

runs:
  using: docker
  image: Dockerfile

# == inputs and outputs ==

inputs:
  name:
    required: false
    description: the person/thing you want to greet
    default: World

outputs:
  phrase:
    description: output variable
